### ISSUE TITLE
Get some test data

### ISSUE THREAD

**Issue by fa-me** [Sh4pe/pynance#14]
create some files with typical input data, as csv or similar

**Comment by Sh4pe** [comment]
What do you think, should we create them manually once or write some small code that produces test data? I think the latter might be a bit overkill for now but will surely come in handy later.

**Comment by Sh4pe** [comment]
I think after #22, this issue is solved because we have some initial test data in the repo now. Do you agree, @fa-me? IMO we can close this.

**Comment by fa-me** [comment]
the test data we have is minimal, especially if we want to test performance, we would need larger files. I think a creation tool will be necessary, but creating it will be as complex as decyphering the data itself, I think. That's something for another milestone I think...
