### ISSUE TITLE
add requirements.txt

### ISSUE THREAD

**Issue by fa-me** [Sh4pe/pynance#20]
* file makes dependecies visible
* [Example file](https://pip.pypa.io/en/stable/reference/pip_install/?highlight=requirements.txt#example-requirements-file)
* Can be run in .travis.yml via `pip install -r requirements.txt`
* [dependency graph](https://help.github.com/articles/listing-the-packages-that-a-repository-depends-on/)

**Comment by fa-me** [comment]
on the other hand, maybe we should switch to conda right away and use the environment.yml from conda.
should work with travis.yml as well - see [here](https://docs.conda.io/projects/conda/en/master/user-guide/tasks/use-conda-with-travis-ci.html)

**Comment by Sh4pe** [comment]
I really like the idea to store the dependencies. From my professional work, I only know and understand how the `requirements.txt` works. And for all purposes that I've encountered during my work, the `requirements.txt` was sufficient. So I fully agree with all 4 bullets of this issue.

I don't really understand `conda` fully yet. If you can store dependencies the same way as in a `requirements.txt` with `conda` too, we might go with `conda` as well. You have more experience there as well.

One point that might be in favour of `requirements.txt` is that `pip` seems to be included in the standard Python distribution, whereas `conda` is a special (and quite large) additional system.
