### ISSUE TITLE
Formalize the workflow

### ISSUE THREAD

**Issue by Sh4pe** [Sh4pe/pynance#4]
On 2019-01-20, we've talked about the raw workflow. This should be formalized in order to have a rough idea of the design, so that we can start from there. 

Format: maybe in Markdown, maybe as a graph... not yet specified.

<img src="https://github.com/Sh4pe/pynance/blob/b7ba4abe3631b64ae1fcf0955f0eca6130b0436e/docs/structure.png?raw=true" />

See [graph](https://github.com/Sh4pe/pynance/blob/b7ba4abe3631b64ae1fcf0955f0eca6130b0436e/docs/structure.png).

**Comment by fa-me** [comment]
identified four players: user, frontend, lib, db
in my eyes the hardest part will be separating frontend and lib, without needing heavy communication between the two
