### ISSUE TITLE
Decide data structure for the raw transaction data

### ISSUE THREAD

**Issue by Sh4pe** [Sh4pe/pynance#5]
We want to store it as pandas DataFrame, but

* which columns are needed?
* is time an index?
* ...?

We should both brainstorm this and come to a decision.

**Comment by Sh4pe** [comment]
cc @fa-me

**Comment by Sh4pe** [comment]
See also #6

**Comment by fa-me** [comment]
turns out we're not quite sure about this yet.
we need at least one additional column imho: origin or something like this, which defines what type the file was where the data came from

**Comment by fa-me** [comment]
mostly resolved with #28 
problems with category will be discussed later in another issue
